## wleku's chat config plugin
## Original author by wleku.

## Format chat event
format: "§7%player% §8> §f%message%"

welcomeEvent: true
welcomeMessage: ""

## Quit message replacement
quitReplace: true
quitMessage: "§c[-] %player% leaved from server"

## Join message replacement
joinReplace: true
joinMessage: "§a[+] %player% joined to server"

## :loc: event
locEvent: true
locFormat: "[ %posX%,  %posY%,  %posZ% ]"

firstWorld: "world"
secondWorld: "world_nether"
thirdWorld: "world_the_end"

firstColor: "§a"
secondColor: "§4"
thirdColor: "§5"

## Ping players
## pingEvent: true
## pingFormat: "[ %X%, %Y%, %Z% ]"